export { default as Navbar } from "./Navbar";
export { default as Cryptos } from "./Cryptos";
export { default as Homepage } from "./Homepage";
export { default as CryptoDetails } from "./CryptoDetails";
export { default as News } from "./News";
export { default as Trade } from "./trading/Trade";
export { default as Loader } from "./Loader";
export { default as Profile } from "./Profile";
export { default as About } from "./About";
